# Generated by Django 4.2.19 on 2025-02-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0002_hotels_activity_hotels_address_hotels_alt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotels",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
