# Generated by Django 4.2.19 on 2025-02-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0003_hotels_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotels",
            name="price",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
