# Generated by Django 4.2.19 on 2025-02-25 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0004_alter_hotels_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rooms",
            fields=[
                ("room_id", models.AutoField(primary_key=True, serialize=False)),
                ("room_type", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=20)),
                ("availability", models.BooleanField(default=False)),
                (
                    "hotel_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotels.hotels"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Geo",
            fields=[
                ("geo_id", models.AutoField(primary_key=True, serialize=False)),
                ("lat", models.CharField(max_length=20)),
                ("lon", models.CharField(max_length=20)),
                (
                    "hotel_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotels.hotels"
                    ),
                ),
            ],
        ),
    ]
