# Generated by Django 4.2.19 on 2025-02-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0006_remove_geo_hotel_id_remove_rooms_hotel_id_geo_hotel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotels",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
