# Generated by Django 4.2.19 on 2025-02-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0007_alter_hotels_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotels",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
