# Generated by Django 4.2.19 on 2025-03-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0008_alter_hotels_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Hotels",
            new_name="Hotel",
        ),
        migrations.RenameModel(
            old_name="Rooms",
            new_name="Room",
        ),
    ]
