# Generated by Django 4.2.19 on 2025-03-03 08:47

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0009_rename_hotels_hotel_rename_rooms_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("reservation_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=100)),
                ("zip", models.CharField(max_length=10)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "hotel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="hotels.hotel",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="hotels.room",
                    ),
                ),
            ],
        ),
    ]
